### ISSUE TITLE
Check for other non-FV2 enabled users

### ISSUE THREAD

**Issue by jbaker10** [tburgin/FV2AuthPlugin#1]
Scenario: AuthPlugin is installed after the fact of another user logging in and forgetting to be added to FV2-enabled users.

AuthPlugin runs, notices there is another user not authenticated after comparing dscl output (or whatever mechanism) to fdesetup list and prompts if we want to enable that user as well.

**Comment by tburgin** [comment]
kind of eliminates the single sign on idea...
