### ISSUE TITLE
Change FV2AuthPluginMechanism methods to private

### ISSUE THREAD

**Issue by tburgin** [tburgin/FV2AuthPlugin#9]
This allows for the use of class `@property`s. This way I don't have to pass around the `MechanismRecord` to public methods. Make `MechanismRecord` a `@property` and it can be available to all the class methods.

**Comment by tburgin** [comment]
https://github.com/tburgin/FV2AuthPlugin/releases/tag/v0.2.3

**Comment by tburgin** [comment]
Who cares pass it around!

**Comment by jbaker10** [comment]
:+1:
